### ISSUE TITLE
Delete all the Javascript Files and other Files

### ISSUE THREAD

**Issue by noahklowden** [Geo-Mafia/Geo-Mafia#44]
We have several no longer useful Javascript files and a few other out of date ones that are not referenced that should be purged to clean up our files. These should be removed.

**Comment by jasulcaf** [comment]
Do after PR #41 is merged

**Comment by jasulcaf** [comment]
Removed the majority of excess .js files that were in the code for frontend. There are only two left, one is inside the player folder which is the location class declaration file (which was written to get the geolocation plugin but wasn't tested nor converted over to .ts). The other is in the tests folder which seems to be the map tests.
@nd1az or @corian-jal, could you take a look at the tests folder and see if we leave that map test as a .js rather than a .ts? 

Otherwise, good for a PR.

**Comment by nd1az** [comment]
I removed all the ng generated test files so that doesn't get confusing. I also propose moving the code from the class_declaration files into the component files and then deleting them so that we don't have redundant files.

**Comment by noahklowden** [comment]
Between #64 and #65 this should be completely resolved.
