### ISSUE TITLE
Game Class Vote Handling

### ISSUE THREAD

**Issue by noahklowden** [Geo-Mafia/Geo-Mafia#46]
The game class should be able to handle the voting scenarios for the game. This involves 
- counting the number of votes on each person
- having a timer that will run the vote at a certain time interval
- killing the voted out player
- reseting the number of votes at the end of the day

After these are done a test issue should be created.

**Comment by jasulcaf** [comment]
Created a branch for this issue

**Comment by jasulcaf** [comment]
Added functionality for the vote process. This entails going through all the players, counting the number of votes that they have received, determine if they get voted off or not (if number of votes is over half of all remaining players, voted off; otherwise they are still safe), and resetting their votes afterwards.
Still have to do the logic of having a timer, but @noahklowden will work on that; and there is also the matter of unit testing.

**Comment by jasulcaf** [comment]
I will also make an explicit note, the functionality needs Issue #47 to have been merged as we use the function `playersRemaining` that they implemented.

**Comment by jasulcaf** [comment]
Modified the test file, fixed a ton of syntax errors. Will want to leave these tests commented out for this branch since it requires functions that will be done in another branch. This serves as a reminder that there will need to be a separate issue so that the tests can be uncommented out and further tested to see if they pass or not.
