### ISSUE TITLE
Fixing the issues present with Map and Snapshot Class

### ISSUE THREAD

**Issue by nd1az** [Geo-Mafia/Geo-Mafia#62]
Adjusting the Snapshot Class to accommodate the changes that were recently made to the bubble class

**Comment by nd1az** [comment]
I added the functionality to grab and copy a playerArray from the content variable and adjusted the tests to go with this
A Snapshot should only have the name of the bubble a `Player` died in and the list of players present, so I got rid of returning a whole bubble since that did not seem necessary to the way a Snapshot gets displayed.
That being said it is in a separate folder. I am confused if  it is meant to be a component of its own kind or just a class declaration(?)

**Comment by Anna-Bele** [comment]
> I added the functionality to grab and copy a playerArray from the content variable and adjusted the tests to go with this A Snapshot should only have the name of the bubble a `Player` died in and the list of players present, so I got rid of returning a whole bubble since that did not seem necessary to the way a Snapshot would be displayed. That being said it is in a separate folder. I am confused if it is meant to be a component of its own kind or just a class declaration(?)

I don't know why you are saying you added the functionality to grab and copy a playerArray from the content variable. This functionality was already implemented, and all tests were passing before you changed the Map implementation. I see you only edited line 25 of the snapshot class, but this is only because you changed the name of one method inside the Map class, so I'm confused about which functionality you are adding. Also, you have overwritten the original constructor of the snapshot content in a way that will cause a shallow copy of the bubble contents. This was originally handled by using the slice() function when the player list is actually a list, but now you will also want to implement a deep copy of playerlist by creating a new map and migrating the player content into the new map. You said you had adjusted the tests, but you only edited line 30 and line 42 of the snapshot list by changing the name of one field of the Bubble, as you did to the snapshot class. The tests were originally implemented so that for some test cases, the player list will be converted to a map first, and then we do the test using this newly created map. However, tests are failing because of your change of the list to a map, and you should also modify the tests to pass. When you change some parts of the code, you want to ensure no code is broken by the changes. Additionally, you changed some function return values of the Map class, which is another reason why some snapshot tests are failing because of the change.

I do appreciate your advice of only keeping the player array and not other bubble information in the snapshot class. However, I will not fix any snapshot implementations before all the map and campus map tests are passing and you make sure nothing will be changed to these two classes.

**Comment by nd1az** [comment]
Added a Date object string so that the Game class can utilize it in representing when Players died/took a snapshot so I also I added a test to see if the time string was initialized. .
I adjusted the snapshot to create a list of player names as that would make representing player data easier and attempted to make a test function to see if the snapshot_content is changed by any changes made to a Bubble.

**Comment by corian-jal** [comment]
Was fixing the tests for map and snapshot so they'd pass, but there ended up being merge conflicts; I think they were passing but now they're not again.

**Comment by Anna-Bele** [comment]
I can see that all the bubble and snapshot tests are passing. Could you make a pull request for this version of the code?
