### ISSUE TITLE
Create unit tests for player class objects

### ISSUE THREAD

**Issue by noahklowden** [Geo-Mafia/Geo-Mafia#9]
For the first milestone, we should create unit tests for each element of the designed aspects of the player classes. This should include ones for the constructors and major functions for each of the base player, serial killer, and civilian classes.

**Comment by jasulcaf** [comment]
After Pull Request #16  goes through, this Issue will be able to be closed. Things to note that should be taken into consideration:
* The Player Class now has a "vote" field. This is because whenever players vote to eliminate a player at the end of the day, this field will store how many times any specific player has been voted. Then with some Game logic (implemented in the Game Module), the Game would determine who, if anyone, is getting voted off
* The test file that we created will need to be moved to a different path position once the app Pull Request goes through (also mentioned in the Pull Request)
